config/routes.rb
Rails.application.routes.draw do
  resources :contacts 
  root 'contacts#index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :user

  	validates :name, presence: true
  	validates :phone, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts
  mount_uploader :avatar
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def check_user_signed_in
    if current_user == nil
      redirect_to new_user_session_path, alert: 'Phải đăng nhập trước'
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update).concat([:avatar, :name])
    devise_parameter_sanitizer.for(:sign_up).concat([:name])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :check_user_signed_in

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts.page(params[:page]).per(1)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.user = current_user
    if @contact.save
      redirect_to @contact, notice: 'Tạo danh bạ thành công'
    else
      render :new
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      redirect_to @contact, notice: 'Sửa bài thành công'
    else
      render :edit
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    contact = Contact.find(params[:id])
    contact.destroy

    redirect_to contacts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone, :address, :note, :avatar, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  AVATAR_VERSIONS = {
    tiny: {
      :format => "png",
      :width => 20,
      :height => 20,
      :crop => :thumb,
    },
    thumb: {
      :format => "png",
      :width => 64,
      :height => 64,
      :crop => :thumb,
    }
  }

  def render_avatar(user, version)
    class_name = ['avatar', 'avatar-' + version.to_s]

    if user.avatar.full_public_id
      cl_image_tag(user.avatar.full_public_id, AVATAR_VERSIONS[version].merge(class: class_name))
    else
      image_tag 'no_avatar.svg', AVATAR_VERSIONS[version].slice(:width, :height).merge(class: class_name)
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="article-form">
  <h2>Sửa danh bạ: <%= @contact.name %></h2>
  <%= render 'form' %>
</div>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h2>Quản lý danh bạ</h2>
<%= link_to 'Thêm danh bạ', new_contact_path, class: 'btn btn-default btn-sm' %>
<table class="table table-striped">
  <thead>
    <th>Họ tên</th>
    <th>Điện thoại</th>
    <th>Địa chỉ</th>
    <th>Ghi chú</th>
    <th width="50"></th>
    <th width="50"></th>
    <th width="50"></th>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.address %></td>
        <td><%= contact.note %></td>
        <td>
          <%= button_to 'Xem', contact_path(contact), class: 'btn btn-default btn-sm' %>         
        </td>
        <td>
          <%= button_to 'Sửa', edit_contact_path(contact), class: 'btn btn-warning btn-sm' %>          
        </td>
        <td>
          <%= button_to 'Xoá', contact_path(contact), method: :delete, data: { confirm: 'Bạn có muốn xoá danh bạ này không?' }, class: 'btn btn-danger btn-sm' %>
        </td>        
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @contacts %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<div class="article-content">
  <h2>Danh bạ: <%= @contact.name %></h2>
  <%= simple_format @contact.phone %>
  <%= simple_format @contact.address %>
  <%= simple_format @contact.note %>
</div>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>
<% if alert %>
  <div class="alert alert-danger"><%= alert %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p>&copy; 2016 KhoaLD Contact Management, Rails basic.</p>
  </div> <!-- /container -->
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Contact Management', root_path, class: 'navbar-brand' %>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li>
          <%= link_to edit_user_registration_path do %>
            <span class="glyphicon glyphicon-user"></span> Cập nhật thông tin cá nhân
          <% end %>
        </li>
        <li>
          <%= link_to contacts_path do %>
            <span class="glyphicon glyphicon-th-list"></span> Quản lý danh bạ
          <% end %>
        </li>
        <li role="separator" class="divider"></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-out"></span> Đăng xuất
          <% end %>
        </li> 
      <% else %>
        <li><%= link_to 'Đăng nhập' , new_user_session_path %></li>
        <li><%= link_to 'Đăng ký', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <title>Contact Management</title>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="main">
      <div class="container">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>